### PR TITLE
Added binaries for MongoDB 3.6.1; 

### PR DESCRIPTION
**Pull request by joehmchan**
Added binaries for MongoDB 3.6.1.
Changed process starter arguments to support mongod 3.6.1.
Upgraded .NET MongoDB driver to 2.5.

### CODE REVIEW

**Comment by oddball** [comment]
Any progress on this?

**Comment by joehmchan** [comment]
@oddball I don't have Linux / Mac OSX development setup, that's why I didn't have chance to resolve the issues. Any clues?

**Comment by oddball** [comment]
Nope, but it might be related to https://github.com/Mongo2Go/Mongo2Go/issues/47
If you have Docker installed, you could run the tests in a linux docker container

**Comment by JohannesHoppe** [comment]
Hi guys, thanks for the support. Upgrading the binaries is something that can be done at any time - even if other bugs are still open.

Please give me time until Monday. I have to compare the binary content first (right now this is a manual step) and then I can bake a next version.

**Comment by JohannesHoppe** [comment]
Many thanks, Mongo2Go was updated to MongoDB 3.6.1: 
https://www.nuget.org/packages/Mongo2Go/2.2.2

**Pull request merged**
