### PR TITLE
Single node replica set option to enable transactions

### PR DESCRIPTION
**Pull request by gbackmania**
Added option to spin up mongod as a single node replica set so transactions could be enabled.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
This looks like an excellent work. Could you please document this feature?
E.g. a new part in the README with a short introduction and a sample, how to leverage transactions?

**Comment by gbackmania** [comment]
I will update the README document. Thank you!

**Comment by gbackmania** [comment]
@JohannesHoppe - I have updated the README. Please let me know if you have any questions, comments or concerns.

**Comment by JohannesHoppe** [comment]
This is how a PR should look like. I will review everything early next week.

**Comment by gbackmania** [comment]
Hey @JohannesHoppe - Just following up to see if you had a chance to look at the pr.

Thank you,
Mahi

**Comment by heymega** [comment]
Nice work @gbackmania. Its a great feeling looking for a feature in an OSS library and finding a PR delivering it!

**Comment by JohannesHoppe** [comment]
v2.2.8 is out, many thanks! 👍

**Comment by gbackmania** [comment]
Thank you @JohannesHoppe. Appreciate it.

**Pull request merged**
