### PR TITLE
Wired mongo's logs to an injected ILogger

### LINKED ISSUE #94: Feature: Disable (optional) console output
It would be nice if we could just optionally disable all writes. Originally i was using --quiet, but it still logs too much.

### LINKED ISSUE #95: Argument --quiet not working on azure devops
I'm trying configured `MongoDbRunner` to not log messages using this configuration:

`MongoDbRunner.Start(additionalMongodArguments: "--quiet");`
But this didn't work... all log messages are showing on my log.

I'm using Mongo2Go with Xunit... 
Have any way to resolve this? Or what i'm doing wrong?

### LINKED ISSUE #113: Configure logging
Thank you so much for this excellent tool!

My understanding right now is that mongo2go outputs its logs to the console, without possibility to configure them. I also noticed the structure of the logs has changed with v3 (more readable and parsable). Would there be a way to configure the logging generated by the tool? The logs generate a lot of noise in CI output.

I know I could turn the output off by calling `MongoDbRunner.Start(additionalMongodArguments: "--quiet");`, but would there be any way to inject a logger (ideally, a `Microsoft.Extensions.Logging.Abstraction.ILogger`) or [configure it with a builder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerfactory.create?view=dotnet-plat-ext-5.0) (`Action<ILoggingBuilder>`), so that to pipe the logs to something completely customized to our use?

### PR DESCRIPTION
**Pull request by corentinaltepe**
Fixes #113
Fixes #94 
Fixes #95

This PR would allow solving #94 and #95 with the following call, although disabling logs is not the direct purpose of this PR:

```c#
_mongoRunner = MongoDbRunner.Start(logger: NullLogger.Instance);
```

### How it works
When starting the mongod process, the `ProcessControl` evaluates if an `ILogger` has been injected or if it's `null`. If `null`, then MongoRunner works as usual, by wiring the logs to .NET's console and debug outputs. Otherwise, it parses mongo's logs and wires them to the `ILogger`. 

Parsing mongo's logs is a discussable choice. I'm open for discussing this choice. I mainly needed to parse the json logs to get the `severity` so that we would call `ILogger` with the appropriate level.

### Risks and Impacts
- Added 2 new dependencies: `Microsoft.Extensions.Logging.Abstractions` for the `ILogger` interface, and `System.Text.Json` to parse the mongo logs.
- Parsing the mongo logs totally depends on [Mongo's definition of their logging structure](https://docs.mongodb.com/manual/reference/log-messages/#json-log-output-format). If they decide to break the format, we'll have to adapt. Notice an error in their documentation: they reported the `id` property to be a `string`, whereas it is actually an `int`.
- This is slightly unrelated. I removed the argument `string windowTitle` from the `ProcessControl.StartAndWait()` methods, as I noticed they were unused. However, the class and the methods are public, meaning it could break usage if anyone has been using these methods. I believe the class `ProcessControl` should remain `internal`. Is that correct? Do we risk breaking anyone's usage with the changes I made here?

### Performance
I ran this modified version of Mongo2Go on a test suite of 296 passing tests. I have not noticed any significant impact or improvement on execution time of the test suite. Duration kept between 02:00 and 2:20 (parallel), or 20-25 minutes cumulative. No significant change either caused by the logging level or the logging target.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Looks great so far! 

`string windowTitle` ... This is super old and was apparently forgotten at some point.

**Comment by corentinaltepe** [comment]
Thank you very much for your feedback. I believe the PR is ready for review now.

I have not updated the changelog. Should I, or is it something you should do when you next release?

**Comment by JohannesHoppe** [comment]
> updating the changelog
I appreciate any help! 😇

**Comment by JohannesHoppe** [comment]
>  updating the changelog
> > I appreciate any help! 😇

**Comment by corentinaltepe** [comment]
I've added a new entry in the changelog. I'm not sure if this is how you intended to have it. Feel free to correct me.
Thanks again!

**Review by JohannesHoppe — APPROVED** [review]

**Pull request merged**
