### PR TITLE
Update to MongoDB.Driver 2.3.0

### LINKED ISSUE #22: Updating to MongoDb Driver 2.3.0 / .NET 4.5
Would you accept a PR for MongoDb Driver 2.3.0 which also requires a .NET Version >= 4.5?

### PR DESCRIPTION
**Pull request by AlexZeitler**
Update MSpec as well and add MSTest Adapter for MSpec (ReSharper console runner doesn't support 4.6)
Upgraded to .NET 4.6 instead of 4.5 as support for 4.5 has ended.
#closes #22

### CODE REVIEW

**Comment by AlexZeitler** [comment]
@JohannesHoppe It looks like the MSpec runner version at appveyor is outdated.

**Comment by JohannesHoppe** [comment]
Yeah, it never really worked! I should unlink it again! 😄 
I will take a look at your work over the weekend!

(PS. Nice to see you here! ;-))

**Comment by AlexZeitler** [comment]
TBH I removed MSpec from all projects and switched to NUnit.

**Comment by JohannesHoppe** [comment]
But, but... the syntax! 😢

**Comment by AlexZeitler** [comment]
https://gist.github.com/AlexZeitler/4b7470b28a4e78426a0f

**Comment by JohannesHoppe** [comment]
I will never get used to that... R.I.P MSpec! 😢

**Comment by JohannesHoppe** [comment]
But on the other hand, i do 80% JS now. I have Jasmine / Mocha! 😎

**Comment by AlexZeitler** [comment]
Mainly Frontend or Backend (Node)?

**Comment by JohannesHoppe** [comment]
Frontend und Build. Node.js - das wär schon toll! ;-)

**Comment by AlexZeitler** [comment]
Would it help you if I would port the tests to NUnit incl. BDD style context spec?

**Comment by JohannesHoppe** [comment]
Zeitmangel #devspace

But i would not be unhappy, if the test suite would be on a more technical base! :-)

**Comment by JohannesHoppe** [comment]
:tada: https://www.nuget.org/packages/Mongo2Go/1.0.0-beta4

**Comment by AlexZeitler** [comment]
👍

**Pull request merged**
