### PR TITLE
Use zero to get free port

### PR DESCRIPTION
**Pull request by realLiangshiwei**
Resolve https://github.com/Mongo2Go/Mongo2Go/issues/115

Locate a free port on the local machine by binding a socket to an IPEndPoint using IPAddress.Any and port 0. The socket will select a free port.

https://github.com/SeleniumHQ/selenium/blob/e9ba4e3f767a671454f01239d4846a853540bbe5/dotnet/src/webdriver/Internal/PortUtilities.cs#L33

image

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Wow! It's really that easy?!

**Comment by realLiangshiwei** [comment]
Yes, 🌝  by the way, Have you published the 3.1.1 NuGet package?

image

**Comment by JohannesHoppe** [comment]
# 😞 

Screen Shot 2021-04-08 at 10 34 20

**Comment by JohannesHoppe** [comment]
The package Mongo2Go 3.1.1 was recently published on NuGet Gallery!

**Pull request merged**
