### PR TITLE
MongoDownloader tool improvements

### PR DESCRIPTION
**Pull request by 0xced**
* Use [Spectre.Console](https://www.nuget.org/packages/Spectre.Console/) instead of [ShellProgressBar](https://www.nuget.org/packages/ShellProgressBar/) for a much nicer download progress.
* Use [Espresso3389.HttpStream](https://www.nuget.org/packages/Espresso3389.HttpStream/) for much faster extraction of files from zip archives where only the needed bytes are downloaded.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
One can extract files directly from the uploaded zip file? Very cool!

Do you need a new version of Mongo3Go with new binaries, too?

**Review by JohannesHoppe — APPROVED** [review]
👍👍👍

**Comment by 0xced** [comment]
> One can extract files directly from the uploaded zip file? Very cool!

Yeah, that's extremely cool. You can see at the start of the download that the total size of the 6 downloads is 572.7 MB but we end up downloading only 272.7 MB for the required parts only, saving a whopping 300 MB!

> Do you need a new version of Mongo2Go with new binaries, too?

No, I was just having fun playing with Spectre.Console and Espresso3389.HttpStream. 😀

**Comment by JohannesHoppe** [comment]
> No, I was just having fun playing with Spectre.Console and Espresso3389.HttpStream. 😀

This is the right spirit! 😎 👍

**Pull request merged**
